[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 200

fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./deployments" }
]

[rpc_endpoints]
sepolia = "${ETH_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETH_SEPOLIA_SCAN_API_KEY}", url = "${ETH_SEPOLIA_ETHERSCAN_VERIFIER_URL}" }